auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 十年运维打杂人生
url: http://www.xiangduole.com
feed: /atom.xml
author_info: <a href="http://www.xiangduole.com/">运维人生</a>
